from langchain_core.prompts import ChatPromptTemplate

def rephraseDBresults(DBresp):
    template = """
        Create Test scenarios for the following context:

        {context}

        ---

    """
    context_text = "\n\n---\n\n".join([doc.page_content for doc, _score in DBresp])
    prompt_template = ChatPromptTemplate.from_template(template)
    prompt = prompt_template.format(context=context_text)
    return prompt

def rephraseUserinput(user_input):
    template = """
    Consider yourself as an english teacher and make correction for any of the errors in the user input given below. And give only the corrected text and no extra text.
    User input: {userInput}
    """
    prompt_template = ChatPromptTemplate.from_template(template)
    prompt = prompt_template.format(userInput=user_input)
    return prompt

def typeofTS(LLM_TS):
    template = """
        Give me type of test scenarios generated below, in a single word separated by "," and no other text.
        ---

        {context}

        ---

    """
    
    prompt_template = ChatPromptTemplate.from_template(template)
    prompt = prompt_template.format(context=LLM_TS)
    return prompt

def makeCorrection(LLM_TS, suggestion="Make the test scenarios for in-depth testing including all the systems."):
    template = """
        Below is the Test scenario generated by the LLM but the user did not like it. Can you rebuild the test scenarios as per suggestion.
        ---

        {context}

        ---
        Suggestion: {suggestion}

    """
    
    prompt_template = ChatPromptTemplate.from_template(template)
    prompt = prompt_template.format(context=LLM_TS, suggestion=suggestion)
    return prompt

def userLikeTS(DBresp, userLikes=["Edge"]):
    template = """
        Create Test scenarios for the following context:
        Include these test scenarios : {TS_types}
        ----
        
        {context}

        ---

    """
    context_text = "\n\n---\n\n".join([doc.page_content for doc, _score in DBresp])
    TS_types = ",".join([ty for ty in userLikes])
    prompt_template = ChatPromptTemplate.from_template(template)
    prompt = prompt_template.format(TS_types=TS_types, context=context_text)
    return prompt




