import pandas as pd
from MySQL_Handler import MySQL_Handler as MSQL_H
import json

def testscenariostoList(TS):
    s_splitter = '['
    e_splitter = ']'
    start_index = TS.find(s_splitter)
    end_index = TS.rfind(e_splitter)
    scenario_types = []
    test_scenarios = []
    if start_index > -1 and end_index > -1:
        str_dump = TS[start_index : end_index + 1]
        print(str_dump)
        js_list = json.loads(str_dump)

        for dic_str in js_list:
            try:
                ts_t_list = dic_str['Data']
            except:
                ts_t_list = dic_str['data']
            for ts, tp in ts_t_list:
                test_scenarios.append(ts)
                scenario_types.append(tp)
    return test_scenarios, scenario_types


if __name__ == "__main__":
    TS = """

--- Test scenarios generated by LLM ---
Here are the test scenarios and their types in JSON format:

{
    "Data": [
        ["www.example.com", "Equivalence Partitioning"],
        ["example.", "Invalid Input"],
        ["www." , "Boundary Value Analysis"], 
        ["www.example.", "Boundary Value Analysis"],
        ["www.", "Equivalence Partitioning"],
        ["", "Invalid Input"],
        ["www. invalidsuffix.com", "Invalid Input"],
        ["www.example.co.uk", "Equivalence Partitioning"]
    ]
}
"""

    testscenarios, types = testscenariostoList(TS)
    for i in range(len(testscenarios)):
        print(f"{i+1} {testscenarios[i]} -> {types[i]}")