def testScenariosToList(TS):
    filteredTS_list = []
    temp_TS = ""
    for i in range(len(TS)):
        ch1 = TS[i]
        if ch1.isnumeric():
            d_TS = TS[i:]
            other_num = False
            for j in range(len(d_TS)):
                num_text = ""
                ch2 = d_TS[j]
                if not other_num:
                    if ch2.isnumeric():
                        num_text += ch2
                    else:
                        temp_TS += ch2
                        if ch2 == '.':
                            other_num  = True
                else:
                    break
        if len(temp_TS) > 0:
            filteredTS_list.append(temp_TS)
    if len(temp_TS) > 0:
        last_index = temp_TS.rfind("\n")
        if last_index > -1:
            temp_TS = temp_TS[:last_index]
            filteredTS_list.append(temp_TS)
        else:
            filteredTS_list.append(temp_TS)
    return filteredTS_list


if __name__ == "__main__":
    TS = """
--- Test scenarios generated by LLM JSON ---
Here are some test scenarios for the given context:

**Valid Input, Network Connectivity**

1. User input: "google"
Expected output: The program prints a fully qualified domain name (FQDN) like "www.google.com" and attempts to perform a DNS lookup using socket library.
2. User input: "microsoft"
Expected output: Same as scenario 1.

**Invalid Input**

3. User input: "" (empty string)
Expected output: The program prints an error message saying "Input cannot be empty."
4. User input: " invalid" (non-existent domain name)
Expected output: The program attempts to perform a DNS lookup, but since the domain name is invalid, it will print an error message like "❌ Error: Hostname 'www.invalid.com' could not be resolved." and suggest checking the domain name or network connection.

**Network Connectivity Issues**

5. User input: "google" (while running the program on a machine with no internet connectivity)
Expected output: The program attempts to perform a DNS lookup, but since there is no internet connectivity, it will print an error message like "❌ Error: Hostname 'www.google.com' could not be resolved." and suggest checking the domain name or network connection.

Note that I did not include test scenarios for valid input with network issues because the problem description does not specify this scenario explicitly.
"""
    ts_list = testScenariosToList(TS)
    for ts in ts_list:
        print(ts)

